In [1]:
import numpy as np

### 리스트 (혹은 튜플)과의 비교

In [2]:
# 리스트
list1 = [10, 20, 30, 40, 50]
list2 = [60, 70, 80, 90, 100]

In [3]:
# 출력
print(list1)
display(list2)

[10, 20, 30, 40, 50]


[60, 70, 80, 90, 100]

In [4]:
# 리스트와 리스트간의 연산
list3 = list1 + list2
list3

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [5]:
# 리스트와 정수 곱하기
list4 = list1 * 3
list4

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [7]:
# 행렬 생성
array1 = np.array([10,20,30,40,50])
array2 = np.array([60,70,80,90,100])

In [8]:
print(array1)
display(array1)

[10 20 30 40 50]


array([10, 20, 30, 40, 50])

In [9]:
# 행렬간의 더하기 연산
array3 = array1 + array2
array3

array([ 70,  90, 110, 130, 150])

In [10]:
# 행렬과 정수간의 연산
array4 = array1 * 3
array4

array([ 30,  60,  90, 120, 150])