In [2]:
import numpy as np
# 1차원 리스트
list1 = [10,20,30,40]
# 1차원 행렬
# 함수안에 리스트, 튜플, range와 같이 순서를 가지고 데이터를 관리하는 요소를 넣어준다.
array1 = np.array([10,20,30,40,50])
# 타입
print(type(list1))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
print(list1)
display(list1)

[10, 20, 30, 40]


[10, 20, 30, 40]

In [4]:
print(array1)
display(array1)

[10 20 30 40 50]


array([10, 20, 30, 40, 50])

In [5]:
# 2차원 리스트
list2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

# 2차원 행렬
array2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [6]:
print(list2)
print(array2)
display(list2)
display(array2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 행렬과 값의 타입간의 관계

In [8]:
array1 = np.array([10,20,30,40,50])
array2 = np.array([11.11, 22.22, 33.33])

In [9]:
# type 함수를 사용하면 해당 객체의 타입을 파악할 수 있다.
# type 함수로는 행렬이 관리하는 값의 타입을 알 수가 없다.
print(type(array1))
print(type(array2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# 행렬이 관리하는 값의 타입을 파악하고자 한다면 dtype을 사용한다.
print(array1.dtype)
print(array2.dtype)

int64
float64


In [16]:
# 다양한 타입을 지정한 경우
list3 = [True, 100, 11.11]
array3 = np.array([True, 100, 11.11, '문자열'])

display(list3)
display(array3) # 행렬은 같은 형태의 데이터를 다룰 수 있음

# 행렬은 한 가지 타입의 값만 담을 수 있다
# 만약 행렬에 다양한 입의 값을 지정해 주면 표현 범위가 더 넓은 쪽으로 값이 변환 된다.

[True, 100, 11.11]

array(['True', '100', '11.11', '문자열'], dtype='<U32')

In [20]:
# 행렬 생성시 타입을 지정해줄 수 있다.
# 논리형 : bool, 정수 : int, 실수 : float, 문자열 : str
array1 = np.array([-2,-1,0,1,2], dtype='bool' )
array2 = np.array([-2.2, -1.1, 0, 1.1, 2.2], dtype='int')
array3 = np.array([-2,-1,0,1,2], dtype='float')
array4 = np.array([-2,-1,0,1,2], dtype='str')

display(array1)
display(array2)
display(array3)
display(array4)

array([ True,  True, False,  True,  True])

array([-2, -1,  0,  1,  2])

array([-2., -1.,  0.,  1.,  2.])

array(['-2', '-1', '0', '1', '2'], dtype='<U2')

In [21]:
# 이미 생성되어 있는 행렬이 가지고 있는 원소들을 추출하여
# 지정된 타입의 값을 관리하는 새로운 행렬을 생성해준다.
array1 = np.array([10,20,30,40,50])
array2 = array1.astype('str')

display(array1)
display(array2)

array([10, 20, 30, 40, 50])

array(['10', '20', '30', '40', '50'], dtype='<U21')

In [25]:
array1 = np.array([True, 100, 11.11, '문자열'], dtype='object')
array1

array([True, 100, 11.11, '문자열'], dtype=object)

### 행렬 생성 함수

In [26]:
# 관리할 값을 지정하여 행렬을 생성한다
# 리스트, 튜플, range와 같이 순서를 통해 값을 관리하는 요소를 넣어준다.
array1 = np.array([10,20,30,40,50])
array1

array([10, 20, 30, 40, 50])

In [28]:
# 0 행렬
# 원소가 0으로 채워진 행렬

# 0이 5개 있는 1차원 행렬
array1 = np.zeros(5)
display(array1)

# 0으로 채워진 3행 4열 행렬
# 행렬의 행의 수와 열의 수를 리스트에 담아 넣어준다
array2 = np.zeros([3,4])
display(array2)

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# 원소가 1로 채워진 행렬

# 1이 5개 있는 1차원 행렬
# 1의 개수를 지정한다
array4 = np.ones(5)
display(array4)

# 1로 채워진 3행 4열행렬
# 행렬의 행의수와 열의수를 리스트로 지정해준다\
array5 = np.ones([3,4])
display(array5)

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
# 숫자 n 으로 채워진 행렬

# 7이 5개 있는 1차원 행렬
# (숫자의 개수, 채울 숫자)
array6 = np.full(5,7)
display(array6)

# 7로 채워진 3행 4열 행렬
# ([행의 수, 열의 수], 채울 숫자)
array7 = np.full([3,4],7)
display(array7)

array([7, 7, 7, 7, 7])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [44]:
# 랜덤값으로 채워진 행렬을 생성한다
# 0 <= n <1

# 랜덤 숫자 5개로 이루어진 1차원 행렬
array8 = np.random.random(5)
display(array8)

# 랜덤 숫자로 구성되어 있는 3행 4열의 행렬
array9 = np.random.random([3,4])
display(array9)

array([0.5525065 , 0.1867497 , 0.92761529, 0.68704928, 0.1744737 ])

array([[0.49647413, 0.82077204, 0.76147082, 0.06042615],
       [0.43856649, 0.60606122, 0.0992382 , 0.3670594 ],
       [0.02362964, 0.58705951, 0.87576266, 0.3906152 ]])

In [51]:
# 범위를 지정하여 정수값을 랜덤하게 가져온다
# 랜덤 정수값 5개로 이루어진 1차원 행렬
# 0 ~ 10 - 1
# 시작값, 끝값, 개수
array10 = np.random.randint(0,10,5)
display(array10)

array([7, 1, 5, 5, 8], dtype=int32)

In [111]:
# 랜덤 정수값으로 채워진 3행 4열 행렬
# 0 ~ 10 - 1 3행 4열
array11 = np.random.randint(0,10,[3,4])
display(array11)

array([[3, 0, 0, 8],
       [2, 0, 7, 1],
       [4, 0, 8, 3]], dtype=int32)

In [61]:
# 특정 범위를 가진 행을 생성한다.
# 1차원 행렬만 가능하다.
array12 = np.arange(6)
display(array12)

array([0, 1, 2, 3, 4, 5])

In [63]:
# 3 ~ 13 -1 까지
array13 = np.arange(3,13)
display(array13)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 행렬의 산술 연산

In [67]:
array1 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [70]:
# 행렬과 행렬간의 산술 연산
# 행렬의 차원과 관계 없이
# 행렬의 각 원소를 1:1 매칭하여 연산을 하고 그 결과가 담겨있는
# 행렬을 반환한다.
# 연산을 하는 두 행렬의 행과 열의 수가 일치해야 한다.
a1 = array1 + array2
a2 = array1 - array2
a3 = array1 * array2
a4 = array1 / array2
a5 = array1 ** array2
a6 = array1 // array2
a7 = array1 % array2

display(a1)
display(a2)
display(a3)
display(a4)
display(a5)
display(a6)
display(a7)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

array([[                10,                400,              27000],
       [           2560000,          312500000,        46656000000],
       [     8235430000000,   1677721600000000, 387420489000000000]])

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
# 행렬과 숫자간의 연산
# 행렬의 각 원소에 숫자와의 연산을 각각 수행한 결과를 반환한다.
a1 = array1 + 10
a2 = array1 - 10
a3 = array1 * 10
a4 = array1 / 10
a5 = array1 ** 10
a6 = array1 // 10
a7 = array1 % 10

display(a1)
display(a2)
display(a3)
display(a4)
display(a5)
display(a6)
display(a7)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

array([[         10000000000,       10240000000000,      590490000000000],
       [   10485760000000000,    97656250000000000,   604661760000000000],
       [ 2824752490000000000, -7709325833709551616, -2025644137419103232]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 인덱싱과 슬라이신
- 인덱싱 : 값 하나를 가져오는 것
- 슬라이싱 : 일부를 가져오는 것

In [72]:
# 1차원 
list1 = [10,20,30,40,50,60,70,80,90,100]
array1 = np.array([10,20,30,40,50,60,70,80,90,100])

In [74]:
# 0 부터 1씩 증가하는 순서값
print(list1[0])
print(list1[1])
print(array1[0])
print(array1[1])

10
20
10
20


In [76]:
# -1 부터 1씩 감소하는 순서값
print(list1[-1])
print(list1[-2])
print(array1[-1])
print(array1[-2])

100
90
100
90


In [79]:
# 2 ~ 6 -1까지
print(list1[2:6])
print(array1[2:6])
# 처음부터 6 -1까지
print(list1[:6])
print(array1[:6])
# 2~ 끝까지
print(list1[2:])
print(array1[2:])

[30, 40, 50, 60]
[30 40 50 60]
[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60]
[30, 40, 50, 60, 70, 80, 90, 100]
[ 30  40  50  60  70  80  90 100]


In [81]:
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

array1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [83]:
# 2행 3열의 데이터를 가져온다
print(list1[1][2])
print(array1[1][2])
print(array1[1,2])

6
6
6


In [86]:
# 1 ~ 3 -1행, 1 ~ 3-1열의 데이터를 가져온다.
display(list1[1:3][1:3])
display(array1[1:3][1:3])
display(array1[1:3, 1:3])

[[7, 8, 9]]

array([[7, 8, 9]])

array([[5, 6],
       [8, 9]])

In [87]:
# 순서를 지정하여 해당 순서에 맞는 값만 가져오기
array1 = np.array([10,20,30,40,50])
array2 = array1[[0,1,4]]
array2

array([10, 20, 50])

In [89]:
# True, False로 구성된 리스트를 넣어주면 True 자리에 해당하는 값만 가져올 수 있다.
# 단, 행렬의 원소의 개수와 행과 열의 구조 모두 동일해야 한다.
array3 = array1[[True, False, True, False, True]]
array3

array([10, 30, 50])

In [103]:
# 0 ~ 99까지 들어있는 행렬을 생성한다.
array1 = np.arange(100)
# array1을 3으로 나눈 나머지가 담긴 행렬을 가져온다
a1 = array1 % 3 
# 3으로 나누는 나머지가 담긴 행렬과 ==0 연산을 수행하여
# 0 인 것은 True, 0이 아닌것은 False로 구성되어 있는 행렬을 가져온다.
a2 = a1 == 0

# 위에서 구한 True나 False가 담긴행렬을 담아준다
array2 = array1[a2]
# 결국에는 3의 배수만 추출한 결과를 얻을 수 있다
array2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [106]:
array1 = np.arange(100)
array2 = array1[array1 % 3 == 0]
array2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])